version: '3.9'

services:
  db:
    image: postgres:15
    hostname: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: candidatos-eleicoes-municipais-2024
    ports:
      - "5432:5432"
    networks:
      - metanet1
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    volumes:
      - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: candidatos-eleicoes-municipais-2024
      MB_DB_PORT: 5432
      MB_DB_USER: admin
      MB_DB_PASS: 12345678
      MB_DB_HOST: postgres
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
    networks:
      - metanet1
networks:
  metanet1:
    driver: bridge
    